#!/usr/bin/env nu
# Regenerate `client.nu` from the pinned Docker Engine API spec.
#
# `client.nu` is FULLY generated by nu-http-client-generator and must never be
# hand-edited. To track a newer Docker API version, drop a fresh spec into
# `spec/docker.swagger.yaml` (see CLAUDE.md) and re-run this script:
#
#     nu scripts/regen.nu
#
# The versioned base URL is derived from the spec's own `basePath`, so bumping
# the spec automatically pins the client to the matching API version.

# resolved relative to this script: <module>/scripts/ -> ../../ is the modules dir
use ../../nu-http-client-generator

const self_path = (path self)

def main [] {
  # this script lives in <module>/scripts/, so the module root is two levels up
  let here = ($self_path | path dirname | path dirname)
  let spec = ([$here spec docker.swagger.yaml] | path join)
  let out = ([$here client.nu] | path join)
  let base = $"http://localhost(open $spec | get basePath)"

  print $"regenerating ($out)"
  print $"  spec: ($spec)"
  print $"  base: ($base)"
  # Generate GET-only for the resource families the wrapper covers. `--tags`
  # drops everything else (swarm, plugins, exec, distribution, …). A few
  # endpoints that share these tags (logs, export, archive, attach-ws, image
  # export, ping, events) are still generated but left unwrapped by mod.nu —
  # the generator has no per-operation filter to exclude them.
  (nu-http-client-generator $spec
    --output $out
    --methods [get]
    --tags [Container Image Network Volume System]
    --no-descriptions
    --no-introspection
    --default-base-url $base
    --default-unix-socket "/var/run/docker.sock"
    --autocompletion-unix-sockets ["/var/run/docker.sock"])

  # Relax each command's generated output type to `any`.
  #
  # The generator emits precise `-> record<...>` / `-> table<...>` return types
  # straight from the spec, and Nushell *runtime-enforces* a command's declared
  # output type. But Docker's live responses routinely drift from the spec schema
  # (extra/missing fields, looser nullability), so an otherwise-valid response
  # fails the type check — `GET /system/df` is one example. The `dockerw` wrapper
  # re-types every result itself, so the client's static types add fragility
  # without value. We rewrite only the public command signature terminators
  # (lines of the form `]: <in> -> <out> {`); helper defs are untouched.
  let relaxed = (
    open --raw $out
    | lines
    | each {|l| $l | str replace --regex '^(\]: (?:nothing|any) -> ).+ \{$' '${1}any {' }
    | str join "\n"
  )
  $relaxed | save --force $out
  let n = ($relaxed | lines | where {|l| $l =~ '^\]: (nothing|any) -> any \{$'} | length)
  print $"done: ($relaxed | lines | length) lines, ($n) commands relaxed to `-> any`"
}
